default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  password: <%= Rails.application.credentials.db_password %>

development:
  <<: *default
  database: timesheet_dev
  username: timesheet_dev_user
  host: 127.0.0.1


test:
  <<: *default
  database: timesheet_test
  username: timesheet_test_user
  host: 127.0.0.1

production:
  <<: *default
  database: timesheet_production
  username: timesheet_prod_user
  password: <%= ENV['RN_TIMESHEET_DATABASE_PASSWORD'] %>
  host: definir.site.com.br
